#include "thousandtopics.h"

#define DDSTYPE(n) \
  @topic @final \
  struct DDSType##n { \
    unsigned long v; \
  };

DDSTYPE(0)
DDSTYPE(1)
DDSTYPE(2)
DDSTYPE(3)
DDSTYPE(4)
DDSTYPE(5)
DDSTYPE(6)
DDSTYPE(7)
DDSTYPE(8)
DDSTYPE(9)
DDSTYPE(10)
DDSTYPE(11)
DDSTYPE(12)
DDSTYPE(13)
DDSTYPE(14)
DDSTYPE(15)
DDSTYPE(16)
DDSTYPE(17)
DDSTYPE(18)
DDSTYPE(19)
#if MAX_TOPICS >= 20
DDSTYPE(20)
DDSTYPE(21)
DDSTYPE(22)
DDSTYPE(23)
DDSTYPE(24)
DDSTYPE(25)
DDSTYPE(26)
DDSTYPE(27)
DDSTYPE(28)
DDSTYPE(29)
DDSTYPE(30)
DDSTYPE(31)
DDSTYPE(32)
DDSTYPE(33)
DDSTYPE(34)
DDSTYPE(35)
DDSTYPE(36)
DDSTYPE(37)
DDSTYPE(38)
DDSTYPE(39)
DDSTYPE(40)
DDSTYPE(41)
DDSTYPE(42)
DDSTYPE(43)
DDSTYPE(44)
DDSTYPE(45)
DDSTYPE(46)
DDSTYPE(47)
DDSTYPE(48)
DDSTYPE(49)
#endif
#if MAX_TOPICS >= 50
DDSTYPE(50)
DDSTYPE(51)
DDSTYPE(52)
DDSTYPE(53)
DDSTYPE(54)
DDSTYPE(55)
DDSTYPE(56)
DDSTYPE(57)
DDSTYPE(58)
DDSTYPE(59)
DDSTYPE(60)
DDSTYPE(61)
DDSTYPE(62)
DDSTYPE(63)
DDSTYPE(64)
DDSTYPE(65)
DDSTYPE(66)
DDSTYPE(67)
DDSTYPE(68)
DDSTYPE(69)
DDSTYPE(70)
DDSTYPE(71)
DDSTYPE(72)
DDSTYPE(73)
DDSTYPE(74)
DDSTYPE(75)
DDSTYPE(76)
DDSTYPE(77)
DDSTYPE(78)
DDSTYPE(79)
DDSTYPE(80)
DDSTYPE(81)
DDSTYPE(82)
DDSTYPE(83)
DDSTYPE(84)
DDSTYPE(85)
DDSTYPE(86)
DDSTYPE(87)
DDSTYPE(88)
DDSTYPE(89)
DDSTYPE(90)
DDSTYPE(91)
DDSTYPE(92)
DDSTYPE(93)
DDSTYPE(94)
DDSTYPE(95)
DDSTYPE(96)
DDSTYPE(97)
DDSTYPE(98)
DDSTYPE(99)
#endif
#if MAX_TOPICS >= 100
DDSTYPE(100)
DDSTYPE(101)
DDSTYPE(102)
DDSTYPE(103)
DDSTYPE(104)
DDSTYPE(105)
DDSTYPE(106)
DDSTYPE(107)
DDSTYPE(108)
DDSTYPE(109)
DDSTYPE(110)
DDSTYPE(111)
DDSTYPE(112)
DDSTYPE(113)
DDSTYPE(114)
DDSTYPE(115)
DDSTYPE(116)
DDSTYPE(117)
DDSTYPE(118)
DDSTYPE(119)
DDSTYPE(120)
DDSTYPE(121)
DDSTYPE(122)
DDSTYPE(123)
DDSTYPE(124)
DDSTYPE(125)
DDSTYPE(126)
DDSTYPE(127)
DDSTYPE(128)
DDSTYPE(129)
DDSTYPE(130)
DDSTYPE(131)
DDSTYPE(132)
DDSTYPE(133)
DDSTYPE(134)
DDSTYPE(135)
DDSTYPE(136)
DDSTYPE(137)
DDSTYPE(138)
DDSTYPE(139)
DDSTYPE(140)
DDSTYPE(141)
DDSTYPE(142)
DDSTYPE(143)
DDSTYPE(144)
DDSTYPE(145)
DDSTYPE(146)
DDSTYPE(147)
DDSTYPE(148)
DDSTYPE(149)
DDSTYPE(150)
DDSTYPE(151)
DDSTYPE(152)
DDSTYPE(153)
DDSTYPE(154)
DDSTYPE(155)
DDSTYPE(156)
DDSTYPE(157)
DDSTYPE(158)
DDSTYPE(159)
DDSTYPE(160)
DDSTYPE(161)
DDSTYPE(162)
DDSTYPE(163)
DDSTYPE(164)
DDSTYPE(165)
DDSTYPE(166)
DDSTYPE(167)
DDSTYPE(168)
DDSTYPE(169)
DDSTYPE(170)
DDSTYPE(171)
DDSTYPE(172)
DDSTYPE(173)
DDSTYPE(174)
DDSTYPE(175)
DDSTYPE(176)
DDSTYPE(177)
DDSTYPE(178)
DDSTYPE(179)
DDSTYPE(180)
DDSTYPE(181)
DDSTYPE(182)
DDSTYPE(183)
DDSTYPE(184)
DDSTYPE(185)
DDSTYPE(186)
DDSTYPE(187)
DDSTYPE(188)
DDSTYPE(189)
DDSTYPE(190)
DDSTYPE(191)
DDSTYPE(192)
DDSTYPE(193)
DDSTYPE(194)
DDSTYPE(195)
DDSTYPE(196)
DDSTYPE(197)
DDSTYPE(198)
DDSTYPE(199)
DDSTYPE(200)
DDSTYPE(201)
DDSTYPE(202)
DDSTYPE(203)
DDSTYPE(204)
DDSTYPE(205)
DDSTYPE(206)
DDSTYPE(207)
DDSTYPE(208)
DDSTYPE(209)
DDSTYPE(210)
DDSTYPE(211)
DDSTYPE(212)
DDSTYPE(213)
DDSTYPE(214)
DDSTYPE(215)
DDSTYPE(216)
DDSTYPE(217)
DDSTYPE(218)
DDSTYPE(219)
DDSTYPE(220)
DDSTYPE(221)
DDSTYPE(222)
DDSTYPE(223)
DDSTYPE(224)
DDSTYPE(225)
DDSTYPE(226)
DDSTYPE(227)
DDSTYPE(228)
DDSTYPE(229)
DDSTYPE(230)
DDSTYPE(231)
DDSTYPE(232)
DDSTYPE(233)
DDSTYPE(234)
DDSTYPE(235)
DDSTYPE(236)
DDSTYPE(237)
DDSTYPE(238)
DDSTYPE(239)
DDSTYPE(240)
DDSTYPE(241)
DDSTYPE(242)
DDSTYPE(243)
DDSTYPE(244)
DDSTYPE(245)
DDSTYPE(246)
DDSTYPE(247)
DDSTYPE(248)
DDSTYPE(249)
DDSTYPE(250)
DDSTYPE(251)
DDSTYPE(252)
DDSTYPE(253)
DDSTYPE(254)
DDSTYPE(255)
DDSTYPE(256)
DDSTYPE(257)
DDSTYPE(258)
DDSTYPE(259)
DDSTYPE(260)
DDSTYPE(261)
DDSTYPE(262)
DDSTYPE(263)
DDSTYPE(264)
DDSTYPE(265)
DDSTYPE(266)
DDSTYPE(267)
DDSTYPE(268)
DDSTYPE(269)
DDSTYPE(270)
DDSTYPE(271)
DDSTYPE(272)
DDSTYPE(273)
DDSTYPE(274)
DDSTYPE(275)
DDSTYPE(276)
DDSTYPE(277)
DDSTYPE(278)
DDSTYPE(279)
DDSTYPE(280)
DDSTYPE(281)
DDSTYPE(282)
DDSTYPE(283)
DDSTYPE(284)
DDSTYPE(285)
DDSTYPE(286)
DDSTYPE(287)
DDSTYPE(288)
DDSTYPE(289)
DDSTYPE(290)
DDSTYPE(291)
DDSTYPE(292)
DDSTYPE(293)
DDSTYPE(294)
DDSTYPE(295)
DDSTYPE(296)
DDSTYPE(297)
DDSTYPE(298)
DDSTYPE(299)
DDSTYPE(300)
DDSTYPE(301)
DDSTYPE(302)
DDSTYPE(303)
DDSTYPE(304)
DDSTYPE(305)
DDSTYPE(306)
DDSTYPE(307)
DDSTYPE(308)
DDSTYPE(309)
DDSTYPE(310)
DDSTYPE(311)
DDSTYPE(312)
DDSTYPE(313)
DDSTYPE(314)
DDSTYPE(315)
DDSTYPE(316)
DDSTYPE(317)
DDSTYPE(318)
DDSTYPE(319)
DDSTYPE(320)
DDSTYPE(321)
DDSTYPE(322)
DDSTYPE(323)
DDSTYPE(324)
DDSTYPE(325)
DDSTYPE(326)
DDSTYPE(327)
DDSTYPE(328)
DDSTYPE(329)
DDSTYPE(330)
DDSTYPE(331)
DDSTYPE(332)
DDSTYPE(333)
DDSTYPE(334)
DDSTYPE(335)
DDSTYPE(336)
DDSTYPE(337)
DDSTYPE(338)
DDSTYPE(339)
DDSTYPE(340)
DDSTYPE(341)
DDSTYPE(342)
DDSTYPE(343)
DDSTYPE(344)
DDSTYPE(345)
DDSTYPE(346)
DDSTYPE(347)
DDSTYPE(348)
DDSTYPE(349)
DDSTYPE(350)
DDSTYPE(351)
DDSTYPE(352)
DDSTYPE(353)
DDSTYPE(354)
DDSTYPE(355)
DDSTYPE(356)
DDSTYPE(357)
DDSTYPE(358)
DDSTYPE(359)
DDSTYPE(360)
DDSTYPE(361)
DDSTYPE(362)
DDSTYPE(363)
DDSTYPE(364)
DDSTYPE(365)
DDSTYPE(366)
DDSTYPE(367)
DDSTYPE(368)
DDSTYPE(369)
DDSTYPE(370)
DDSTYPE(371)
DDSTYPE(372)
DDSTYPE(373)
DDSTYPE(374)
DDSTYPE(375)
DDSTYPE(376)
DDSTYPE(377)
DDSTYPE(378)
DDSTYPE(379)
DDSTYPE(380)
DDSTYPE(381)
DDSTYPE(382)
DDSTYPE(383)
DDSTYPE(384)
DDSTYPE(385)
DDSTYPE(386)
DDSTYPE(387)
DDSTYPE(388)
DDSTYPE(389)
DDSTYPE(390)
DDSTYPE(391)
DDSTYPE(392)
DDSTYPE(393)
DDSTYPE(394)
DDSTYPE(395)
DDSTYPE(396)
DDSTYPE(397)
DDSTYPE(398)
DDSTYPE(399)
DDSTYPE(400)
DDSTYPE(401)
DDSTYPE(402)
DDSTYPE(403)
DDSTYPE(404)
DDSTYPE(405)
DDSTYPE(406)
DDSTYPE(407)
DDSTYPE(408)
DDSTYPE(409)
DDSTYPE(410)
DDSTYPE(411)
DDSTYPE(412)
DDSTYPE(413)
DDSTYPE(414)
DDSTYPE(415)
DDSTYPE(416)
DDSTYPE(417)
DDSTYPE(418)
DDSTYPE(419)
DDSTYPE(420)
DDSTYPE(421)
DDSTYPE(422)
DDSTYPE(423)
DDSTYPE(424)
DDSTYPE(425)
DDSTYPE(426)
DDSTYPE(427)
DDSTYPE(428)
DDSTYPE(429)
DDSTYPE(430)
DDSTYPE(431)
DDSTYPE(432)
DDSTYPE(433)
DDSTYPE(434)
DDSTYPE(435)
DDSTYPE(436)
DDSTYPE(437)
DDSTYPE(438)
DDSTYPE(439)
DDSTYPE(440)
DDSTYPE(441)
DDSTYPE(442)
DDSTYPE(443)
DDSTYPE(444)
DDSTYPE(445)
DDSTYPE(446)
DDSTYPE(447)
DDSTYPE(448)
DDSTYPE(449)
DDSTYPE(450)
DDSTYPE(451)
DDSTYPE(452)
DDSTYPE(453)
DDSTYPE(454)
DDSTYPE(455)
DDSTYPE(456)
DDSTYPE(457)
DDSTYPE(458)
DDSTYPE(459)
DDSTYPE(460)
DDSTYPE(461)
DDSTYPE(462)
DDSTYPE(463)
DDSTYPE(464)
DDSTYPE(465)
DDSTYPE(466)
DDSTYPE(467)
DDSTYPE(468)
DDSTYPE(469)
DDSTYPE(470)
DDSTYPE(471)
DDSTYPE(472)
DDSTYPE(473)
DDSTYPE(474)
DDSTYPE(475)
DDSTYPE(476)
DDSTYPE(477)
DDSTYPE(478)
DDSTYPE(479)
DDSTYPE(480)
DDSTYPE(481)
DDSTYPE(482)
DDSTYPE(483)
DDSTYPE(484)
DDSTYPE(485)
DDSTYPE(486)
DDSTYPE(487)
DDSTYPE(488)
DDSTYPE(489)
DDSTYPE(490)
DDSTYPE(491)
DDSTYPE(492)
DDSTYPE(493)
DDSTYPE(494)
DDSTYPE(495)
DDSTYPE(496)
DDSTYPE(497)
DDSTYPE(498)
DDSTYPE(499)
DDSTYPE(500)
DDSTYPE(501)
DDSTYPE(502)
DDSTYPE(503)
DDSTYPE(504)
DDSTYPE(505)
DDSTYPE(506)
DDSTYPE(507)
DDSTYPE(508)
DDSTYPE(509)
DDSTYPE(510)
DDSTYPE(511)
DDSTYPE(512)
DDSTYPE(513)
DDSTYPE(514)
DDSTYPE(515)
DDSTYPE(516)
DDSTYPE(517)
DDSTYPE(518)
DDSTYPE(519)
DDSTYPE(520)
DDSTYPE(521)
DDSTYPE(522)
DDSTYPE(523)
DDSTYPE(524)
DDSTYPE(525)
DDSTYPE(526)
DDSTYPE(527)
DDSTYPE(528)
DDSTYPE(529)
DDSTYPE(530)
DDSTYPE(531)
DDSTYPE(532)
DDSTYPE(533)
DDSTYPE(534)
DDSTYPE(535)
DDSTYPE(536)
DDSTYPE(537)
DDSTYPE(538)
DDSTYPE(539)
DDSTYPE(540)
DDSTYPE(541)
DDSTYPE(542)
DDSTYPE(543)
DDSTYPE(544)
DDSTYPE(545)
DDSTYPE(546)
DDSTYPE(547)
DDSTYPE(548)
DDSTYPE(549)
DDSTYPE(550)
DDSTYPE(551)
DDSTYPE(552)
DDSTYPE(553)
DDSTYPE(554)
DDSTYPE(555)
DDSTYPE(556)
DDSTYPE(557)
DDSTYPE(558)
DDSTYPE(559)
DDSTYPE(560)
DDSTYPE(561)
DDSTYPE(562)
DDSTYPE(563)
DDSTYPE(564)
DDSTYPE(565)
DDSTYPE(566)
DDSTYPE(567)
DDSTYPE(568)
DDSTYPE(569)
DDSTYPE(570)
DDSTYPE(571)
DDSTYPE(572)
DDSTYPE(573)
DDSTYPE(574)
DDSTYPE(575)
DDSTYPE(576)
DDSTYPE(577)
DDSTYPE(578)
DDSTYPE(579)
DDSTYPE(580)
DDSTYPE(581)
DDSTYPE(582)
DDSTYPE(583)
DDSTYPE(584)
DDSTYPE(585)
DDSTYPE(586)
DDSTYPE(587)
DDSTYPE(588)
DDSTYPE(589)
DDSTYPE(590)
DDSTYPE(591)
DDSTYPE(592)
DDSTYPE(593)
DDSTYPE(594)
DDSTYPE(595)
DDSTYPE(596)
DDSTYPE(597)
DDSTYPE(598)
DDSTYPE(599)
DDSTYPE(600)
DDSTYPE(601)
DDSTYPE(602)
DDSTYPE(603)
DDSTYPE(604)
DDSTYPE(605)
DDSTYPE(606)
DDSTYPE(607)
DDSTYPE(608)
DDSTYPE(609)
DDSTYPE(610)
DDSTYPE(611)
DDSTYPE(612)
DDSTYPE(613)
DDSTYPE(614)
DDSTYPE(615)
DDSTYPE(616)
DDSTYPE(617)
DDSTYPE(618)
DDSTYPE(619)
DDSTYPE(620)
DDSTYPE(621)
DDSTYPE(622)
DDSTYPE(623)
DDSTYPE(624)
DDSTYPE(625)
DDSTYPE(626)
DDSTYPE(627)
DDSTYPE(628)
DDSTYPE(629)
DDSTYPE(630)
DDSTYPE(631)
DDSTYPE(632)
DDSTYPE(633)
DDSTYPE(634)
DDSTYPE(635)
DDSTYPE(636)
DDSTYPE(637)
DDSTYPE(638)
DDSTYPE(639)
DDSTYPE(640)
DDSTYPE(641)
DDSTYPE(642)
DDSTYPE(643)
DDSTYPE(644)
DDSTYPE(645)
DDSTYPE(646)
DDSTYPE(647)
DDSTYPE(648)
DDSTYPE(649)
DDSTYPE(650)
DDSTYPE(651)
DDSTYPE(652)
DDSTYPE(653)
DDSTYPE(654)
DDSTYPE(655)
DDSTYPE(656)
DDSTYPE(657)
DDSTYPE(658)
DDSTYPE(659)
DDSTYPE(660)
DDSTYPE(661)
DDSTYPE(662)
DDSTYPE(663)
DDSTYPE(664)
DDSTYPE(665)
DDSTYPE(666)
DDSTYPE(667)
DDSTYPE(668)
DDSTYPE(669)
DDSTYPE(670)
DDSTYPE(671)
DDSTYPE(672)
DDSTYPE(673)
DDSTYPE(674)
DDSTYPE(675)
DDSTYPE(676)
DDSTYPE(677)
DDSTYPE(678)
DDSTYPE(679)
DDSTYPE(680)
DDSTYPE(681)
DDSTYPE(682)
DDSTYPE(683)
DDSTYPE(684)
DDSTYPE(685)
DDSTYPE(686)
DDSTYPE(687)
DDSTYPE(688)
DDSTYPE(689)
DDSTYPE(690)
DDSTYPE(691)
DDSTYPE(692)
DDSTYPE(693)
DDSTYPE(694)
DDSTYPE(695)
DDSTYPE(696)
DDSTYPE(697)
DDSTYPE(698)
DDSTYPE(699)
DDSTYPE(700)
DDSTYPE(701)
DDSTYPE(702)
DDSTYPE(703)
DDSTYPE(704)
DDSTYPE(705)
DDSTYPE(706)
DDSTYPE(707)
DDSTYPE(708)
DDSTYPE(709)
DDSTYPE(710)
DDSTYPE(711)
DDSTYPE(712)
DDSTYPE(713)
DDSTYPE(714)
DDSTYPE(715)
DDSTYPE(716)
DDSTYPE(717)
DDSTYPE(718)
DDSTYPE(719)
DDSTYPE(720)
DDSTYPE(721)
DDSTYPE(722)
DDSTYPE(723)
DDSTYPE(724)
DDSTYPE(725)
DDSTYPE(726)
DDSTYPE(727)
DDSTYPE(728)
DDSTYPE(729)
DDSTYPE(730)
DDSTYPE(731)
DDSTYPE(732)
DDSTYPE(733)
DDSTYPE(734)
DDSTYPE(735)
DDSTYPE(736)
DDSTYPE(737)
DDSTYPE(738)
DDSTYPE(739)
DDSTYPE(740)
DDSTYPE(741)
DDSTYPE(742)
DDSTYPE(743)
DDSTYPE(744)
DDSTYPE(745)
DDSTYPE(746)
DDSTYPE(747)
DDSTYPE(748)
DDSTYPE(749)
DDSTYPE(750)
DDSTYPE(751)
DDSTYPE(752)
DDSTYPE(753)
DDSTYPE(754)
DDSTYPE(755)
DDSTYPE(756)
DDSTYPE(757)
DDSTYPE(758)
DDSTYPE(759)
DDSTYPE(760)
DDSTYPE(761)
DDSTYPE(762)
DDSTYPE(763)
DDSTYPE(764)
DDSTYPE(765)
DDSTYPE(766)
DDSTYPE(767)
DDSTYPE(768)
DDSTYPE(769)
DDSTYPE(770)
DDSTYPE(771)
DDSTYPE(772)
DDSTYPE(773)
DDSTYPE(774)
DDSTYPE(775)
DDSTYPE(776)
DDSTYPE(777)
DDSTYPE(778)
DDSTYPE(779)
DDSTYPE(780)
DDSTYPE(781)
DDSTYPE(782)
DDSTYPE(783)
DDSTYPE(784)
DDSTYPE(785)
DDSTYPE(786)
DDSTYPE(787)
DDSTYPE(788)
DDSTYPE(789)
DDSTYPE(790)
DDSTYPE(791)
DDSTYPE(792)
DDSTYPE(793)
DDSTYPE(794)
DDSTYPE(795)
DDSTYPE(796)
DDSTYPE(797)
DDSTYPE(798)
DDSTYPE(799)
DDSTYPE(800)
DDSTYPE(801)
DDSTYPE(802)
DDSTYPE(803)
DDSTYPE(804)
DDSTYPE(805)
DDSTYPE(806)
DDSTYPE(807)
DDSTYPE(808)
DDSTYPE(809)
DDSTYPE(810)
DDSTYPE(811)
DDSTYPE(812)
DDSTYPE(813)
DDSTYPE(814)
DDSTYPE(815)
DDSTYPE(816)
DDSTYPE(817)
DDSTYPE(818)
DDSTYPE(819)
DDSTYPE(820)
DDSTYPE(821)
DDSTYPE(822)
DDSTYPE(823)
DDSTYPE(824)
DDSTYPE(825)
DDSTYPE(826)
DDSTYPE(827)
DDSTYPE(828)
DDSTYPE(829)
DDSTYPE(830)
DDSTYPE(831)
DDSTYPE(832)
DDSTYPE(833)
DDSTYPE(834)
DDSTYPE(835)
DDSTYPE(836)
DDSTYPE(837)
DDSTYPE(838)
DDSTYPE(839)
DDSTYPE(840)
DDSTYPE(841)
DDSTYPE(842)
DDSTYPE(843)
DDSTYPE(844)
DDSTYPE(845)
DDSTYPE(846)
DDSTYPE(847)
DDSTYPE(848)
DDSTYPE(849)
DDSTYPE(850)
DDSTYPE(851)
DDSTYPE(852)
DDSTYPE(853)
DDSTYPE(854)
DDSTYPE(855)
DDSTYPE(856)
DDSTYPE(857)
DDSTYPE(858)
DDSTYPE(859)
DDSTYPE(860)
DDSTYPE(861)
DDSTYPE(862)
DDSTYPE(863)
DDSTYPE(864)
DDSTYPE(865)
DDSTYPE(866)
DDSTYPE(867)
DDSTYPE(868)
DDSTYPE(869)
DDSTYPE(870)
DDSTYPE(871)
DDSTYPE(872)
DDSTYPE(873)
DDSTYPE(874)
DDSTYPE(875)
DDSTYPE(876)
DDSTYPE(877)
DDSTYPE(878)
DDSTYPE(879)
DDSTYPE(880)
DDSTYPE(881)
DDSTYPE(882)
DDSTYPE(883)
DDSTYPE(884)
DDSTYPE(885)
DDSTYPE(886)
DDSTYPE(887)
DDSTYPE(888)
DDSTYPE(889)
DDSTYPE(890)
DDSTYPE(891)
DDSTYPE(892)
DDSTYPE(893)
DDSTYPE(894)
DDSTYPE(895)
DDSTYPE(896)
DDSTYPE(897)
DDSTYPE(898)
DDSTYPE(899)
DDSTYPE(900)
DDSTYPE(901)
DDSTYPE(902)
DDSTYPE(903)
DDSTYPE(904)
DDSTYPE(905)
DDSTYPE(906)
DDSTYPE(907)
DDSTYPE(908)
DDSTYPE(909)
DDSTYPE(910)
DDSTYPE(911)
DDSTYPE(912)
DDSTYPE(913)
DDSTYPE(914)
DDSTYPE(915)
DDSTYPE(916)
DDSTYPE(917)
DDSTYPE(918)
DDSTYPE(919)
DDSTYPE(920)
DDSTYPE(921)
DDSTYPE(922)
DDSTYPE(923)
DDSTYPE(924)
DDSTYPE(925)
DDSTYPE(926)
DDSTYPE(927)
DDSTYPE(928)
DDSTYPE(929)
DDSTYPE(930)
DDSTYPE(931)
DDSTYPE(932)
DDSTYPE(933)
DDSTYPE(934)
DDSTYPE(935)
DDSTYPE(936)
DDSTYPE(937)
DDSTYPE(938)
DDSTYPE(939)
DDSTYPE(940)
DDSTYPE(941)
DDSTYPE(942)
DDSTYPE(943)
DDSTYPE(944)
DDSTYPE(945)
DDSTYPE(946)
DDSTYPE(947)
DDSTYPE(948)
DDSTYPE(949)
DDSTYPE(950)
DDSTYPE(951)
DDSTYPE(952)
DDSTYPE(953)
DDSTYPE(954)
DDSTYPE(955)
DDSTYPE(956)
DDSTYPE(957)
DDSTYPE(958)
DDSTYPE(959)
DDSTYPE(960)
DDSTYPE(961)
DDSTYPE(962)
DDSTYPE(963)
DDSTYPE(964)
DDSTYPE(965)
DDSTYPE(966)
DDSTYPE(967)
DDSTYPE(968)
DDSTYPE(969)
DDSTYPE(970)
DDSTYPE(971)
DDSTYPE(972)
DDSTYPE(973)
DDSTYPE(974)
DDSTYPE(975)
DDSTYPE(976)
DDSTYPE(977)
DDSTYPE(978)
DDSTYPE(979)
DDSTYPE(980)
DDSTYPE(981)
DDSTYPE(982)
DDSTYPE(983)
DDSTYPE(984)
DDSTYPE(985)
DDSTYPE(986)
DDSTYPE(987)
DDSTYPE(988)
DDSTYPE(989)
DDSTYPE(990)
DDSTYPE(991)
DDSTYPE(992)
DDSTYPE(993)
DDSTYPE(994)
DDSTYPE(995)
DDSTYPE(996)
DDSTYPE(997)
DDSTYPE(998)
DDSTYPE(999)
#endif
