#
# Copyright(c) 2020 to 2022 ZettaScale Technology and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#
include(GenerateExportHeader)

set(sources
    src/dds/core/Duration.cpp
    src/dds/core/Exception.cpp
    src/dds/core/Reference.cpp
    src/dds/core/Time.cpp
    src/dds/core/policy/CorePolicy.cpp
    src/dds/core/status/State.cpp
    src/dds/domain/discovery.cpp
    src/dds/domain/find.cpp
    src/dds/pub/pubdiscovery.cpp
    src/dds/sub/subdiscovery.cpp
    src/dds/sub/subfind.cpp
    src/dds/sub/status/DataState.cpp
    src/org/eclipse/cyclonedds/core/Mutex.cpp
    src/org/eclipse/cyclonedds/core/ObjectDelegate.cpp
    src/org/eclipse/cyclonedds/core/DDScObjectDelegate.cpp
    src/org/eclipse/cyclonedds/core/ObjectSet.cpp
    src/org/eclipse/cyclonedds/core/EntityDelegate.cpp
    src/org/eclipse/cyclonedds/core/ReportUtils.cpp
    src/org/eclipse/cyclonedds/core/ListenerDispatcher.cpp
    src/org/eclipse/cyclonedds/core/NoopListener.cpp
    src/org/eclipse/cyclonedds/core/InstanceHandleDelegate.cpp
    src/org/eclipse/cyclonedds/core/EntitySet.cpp
    src/org/eclipse/cyclonedds/core/MiscUtils.cpp
    src/org/eclipse/cyclonedds/core/cdr/fragchain.cpp
    src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
    src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp
    src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp
    src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.cpp
    src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
    src/org/eclipse/cyclonedds/core/cond/ConditionDelegate.cpp
    src/org/eclipse/cyclonedds/core/cond/GuardConditionDelegate.cpp
    src/org/eclipse/cyclonedds/core/cond/StatusConditionDelegate.cpp
    src/org/eclipse/cyclonedds/core/cond/WaitSetDelegate.cpp
    src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
    src/org/eclipse/cyclonedds/domain/Domain.cpp
    src/org/eclipse/cyclonedds/domain/DomainWrap.cpp
    src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
    src/org/eclipse/cyclonedds/domain/DomainParticipantRegistry.cpp
    src/org/eclipse/cyclonedds/domain/qos/DomainParticipantQosDelegate.cpp
    src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
    src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
    src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
    src/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.cpp
    src/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.cpp
    src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
    src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
    src/org/eclipse/cyclonedds/sub/BuiltinSubscriberDelegate.cpp
    src/org/eclipse/cyclonedds/sub/QueryDelegate.cpp
    src/org/eclipse/cyclonedds/sub/SampleInfoImpl.cpp
    src/org/eclipse/cyclonedds/sub/cond/ReadConditionDelegate.cpp
    src/org/eclipse/cyclonedds/sub/cond/QueryConditionDelegate.cpp
    src/org/eclipse/cyclonedds/sub/qos/SubscriberQosDelegate.cpp
    src/org/eclipse/cyclonedds/topic/find.cpp
    src/org/eclipse/cyclonedds/topic/hash.cpp
    src/org/eclipse/cyclonedds/topic/AnyTopicDelegate.cpp
    src/org/eclipse/cyclonedds/topic/FilterDelegate.cpp
    src/org/eclipse/cyclonedds/topic/TopicDescriptionDelegate.cpp
    src/org/eclipse/cyclonedds/topic/qos/TopicQosDelegate.cpp

    include/org/eclipse/cyclonedds/ForwardDeclarations.hpp
    include/org/eclipse/cyclonedds/core/ReportUtils.hpp
    include/org/eclipse/cyclonedds/core/WeakReferenceSet.hpp
    include/org/eclipse/cyclonedds/core/ListenerDispatcher.hpp
    include/org/eclipse/cyclonedds/core/EntityDelegate.hpp
    include/org/eclipse/cyclonedds/core/MiscUtils.hpp
    include/org/eclipse/cyclonedds/core/TimeHelper.hpp
    include/org/eclipse/cyclonedds/core/config.hpp
    include/org/eclipse/cyclonedds/core/status/StatusDelegate.hpp
    include/org/eclipse/cyclonedds/core/cond/StatusConditionDelegate.hpp
    include/org/eclipse/cyclonedds/core/cond/GuardConditionDelegate.hpp
    include/org/eclipse/cyclonedds/core/cond/FunctorHolder.hpp
    include/org/eclipse/cyclonedds/core/cond/ShadowParticipant.hpp
    include/org/eclipse/cyclonedds/core/cond/WaitSetDelegate.hpp
    include/org/eclipse/cyclonedds/core/cond/ConditionDelegate.hpp
    include/org/eclipse/cyclonedds/core/DDScObjectDelegate.hpp
    include/org/eclipse/cyclonedds/core/EntityRegistry.hpp
    include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
    include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp
    include/org/eclipse/cyclonedds/core/cdr/fragchain.hpp
    include/org/eclipse/cyclonedds/core/cdr/cdr_enums.hpp
    include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.hpp
    include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp
    include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.hpp
    include/org/eclipse/cyclonedds/core/EntitySet.hpp
    include/org/eclipse/cyclonedds/core/ScopedLock.hpp
    include/org/eclipse/cyclonedds/core/QosProviderDelegate.hpp
    include/org/eclipse/cyclonedds/core/Mutex.hpp
    include/org/eclipse/cyclonedds/core/ObjectDelegate.hpp
    include/org/eclipse/cyclonedds/core/NoopListener.hpp
    include/org/eclipse/cyclonedds/core/Missing.hpp
    include/org/eclipse/cyclonedds/core/InstanceHandleDelegate.hpp
    include/org/eclipse/cyclonedds/core/policy/QosPolicyCountDelegate.hpp
    include/org/eclipse/cyclonedds/core/policy/Policy.hpp
    include/org/eclipse/cyclonedds/core/policy/PolicyDelegate.hpp
    include/org/eclipse/cyclonedds/core/policy/ProprietaryPolicyKind.hpp
    include/org/eclipse/cyclonedds/core/policy/TPolicy.hpp
    include/org/eclipse/cyclonedds/core/ObjectSet.hpp
    include/org/eclipse/cyclonedds/core/type_helpers.hpp
    include/org/eclipse/cyclonedds/util/ostream_operators.hpp
    include/org/eclipse/cyclonedds/topic/BuiltinTopicKeyDelegate.hpp
    include/org/eclipse/cyclonedds/topic/hash.hpp
    include/org/eclipse/cyclonedds/topic/BuiltinTopicCopy.hpp
    include/org/eclipse/cyclonedds/topic/BuiltinTopic.hpp
    include/org/eclipse/cyclonedds/topic/TBuiltinTopic.hpp
    include/org/eclipse/cyclonedds/topic/qos/TopicQosDelegate.hpp
    include/org/eclipse/cyclonedds/topic/BuiltinTopicTraits.hpp
    include/org/eclipse/cyclonedds/topic/AnyTopicDelegate.hpp
    include/org/eclipse/cyclonedds/topic/discovery.hpp
    include/org/eclipse/cyclonedds/topic/find.hpp
    include/org/eclipse/cyclonedds/topic/TopicListener.hpp
    include/org/eclipse/cyclonedds/topic/datatopic.hpp
    include/org/eclipse/cyclonedds/topic/FilterDelegate.hpp
    include/org/eclipse/cyclonedds/topic/TopicDescriptionDelegate.hpp
    include/org/eclipse/cyclonedds/topic/CDRBlob.hpp
    include/org/eclipse/cyclonedds/topic/AnyTopicListener.hpp
    include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
    include/org/eclipse/cyclonedds/topic/BuiltinTopicDelegate.hpp
    include/org/eclipse/cyclonedds/sub/SampleInfoImpl.hpp
    include/org/eclipse/cyclonedds/sub/qos/SubscriberQosDelegate.hpp
    include/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.hpp
    include/org/eclipse/cyclonedds/sub/cond/QueryConditionDelegate.hpp
    include/org/eclipse/cyclonedds/sub/cond/ReadConditionDelegate.hpp
    include/org/eclipse/cyclonedds/sub/SubscriberDelegate.hpp
    include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
    include/org/eclipse/cyclonedds/sub/BuiltinSubscriberDelegate.hpp
    include/org/eclipse/cyclonedds/sub/GenerationCountImpl.hpp
    include/org/eclipse/cyclonedds/sub/RankImpl.hpp
    include/org/eclipse/cyclonedds/sub/CoherentAccessDelegate.hpp
    include/org/eclipse/cyclonedds/sub/QueryDelegate.hpp
    include/org/eclipse/cyclonedds/pub/PublisherDelegate.hpp
    include/org/eclipse/cyclonedds/pub/SuspendedPublicationDelegate.hpp
    include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
    include/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.hpp
    include/org/eclipse/cyclonedds/pub/CoherentSetDelegate.hpp
    include/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.hpp
    include/org/eclipse/cyclonedds/domain/DomainParticipantRegistry.hpp
    include/org/eclipse/cyclonedds/domain/Domain.hpp
    include/org/eclipse/cyclonedds/domain/DomainParticipantListener.hpp
    include/org/eclipse/cyclonedds/domain/qos/DomainParticipantQosDelegate.hpp
    include/org/eclipse/cyclonedds/domain/DomainWrap.hpp
    include/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.hpp
    include/dds/core/WeakReference.hpp
    include/dds/core/TEntity.hpp
    include/dds/core/External.hpp
    include/dds/core/conformance.hpp
    include/dds/core/ref_traits.hpp
    include/dds/core/TInstanceHandle.hpp
    include/dds/core/Time.hpp
    include/dds/core/refmacros.hpp
    include/dds/core/macros.hpp
    include/dds/core/array.hpp
    include/dds/core/Value.hpp
    include/dds/core/TQosProvider.hpp
    include/dds/core/status/TStatus.hpp
    include/dds/core/status/Status.hpp
    include/dds/core/status/detail/TStatusImpl.hpp
    include/dds/core/status/detail/Status.hpp
    include/dds/core/status/State.hpp
    include/dds/core/InstanceHandle.hpp
    include/dds/core/Reference.hpp
    include/dds/core/cond/TWaitSet.hpp
    include/dds/core/cond/TGuardCondition.hpp
    include/dds/core/cond/TStatusCondition.hpp
    include/dds/core/cond/TCondition.hpp
    include/dds/core/cond/GuardCondition.hpp
    include/dds/core/cond/StatusCondition.hpp
    include/dds/core/cond/detail/TConditionImpl.hpp
    include/dds/core/cond/detail/GuardCondition.hpp
    include/dds/core/cond/detail/StatusCondition.hpp
    include/dds/core/cond/detail/TGuardConditionImpl.hpp
    include/dds/core/cond/detail/TStatusConditionImpl.hpp
    include/dds/core/cond/detail/WaitSet.hpp
    include/dds/core/cond/detail/TWaitSetImpl.hpp
    include/dds/core/cond/detail/Condition.hpp
    include/dds/core/cond/WaitSet.hpp
    include/dds/core/cond/Condition.hpp
    include/dds/core/TEntityQos.hpp
    include/dds/core/detail/TQosProviderImpl.hpp
    include/dds/core/detail/conformance.hpp
    include/dds/core/detail/TEntityQosImpl.hpp
    include/dds/core/detail/ref_traits.hpp
    include/dds/core/detail/macros.hpp
    include/dds/core/detail/WeakReferenceImpl.hpp
    include/dds/core/detail/array.hpp
    include/dds/core/detail/inttypes.hpp
    include/dds/core/detail/ReferenceImpl.hpp
    include/dds/core/detail/Value.hpp
    include/dds/core/detail/InstanceHandle.hpp
    include/dds/core/detail/TInstanceHandleImpl.hpp
    include/dds/core/detail/module_docs.hpp
    include/dds/core/detail/ddscore.hpp
    include/dds/core/detail/QosProvider.hpp
    include/dds/core/detail/TEntityImpl.hpp
    include/dds/core/detail/BuiltinTopicTypes.hpp
    include/dds/core/detail/Entity.hpp
    include/dds/core/Optional.hpp
    include/dds/core/TBuiltinTopicTypes.hpp
    include/dds/core/SafeEnumeration.hpp
    include/dds/core/xtypes/Annotations.hpp
    include/dds/core/xtypes/TDynamicData.hpp
    include/dds/core/xtypes/CollectionTypes.hpp
    include/dds/core/xtypes/TypeKind.hpp
    include/dds/core/xtypes/DynamicType.hpp
    include/dds/core/xtypes/TDynamicType.hpp
    include/dds/core/xtypes/UnionType.hpp
    include/dds/core/xtypes/detail/CollectionTypes.hpp
    include/dds/core/xtypes/detail/DynamicType.hpp
    include/dds/core/xtypes/detail/UnionType.hpp
    include/dds/core/xtypes/detail/StructType.hpp
    include/dds/core/xtypes/detail/Annotation.hpp
    include/dds/core/xtypes/detail/UnionCase.hpp
    include/dds/core/xtypes/detail/DynamicData.hpp
    include/dds/core/xtypes/detail/MemberType.hpp
    include/dds/core/xtypes/detail/TypeProvider.hpp
    include/dds/core/xtypes/detail/PrimitiveTypes.hpp
    include/dds/core/xtypes/StructType.hpp
    include/dds/core/xtypes/UnionCase.hpp
    include/dds/core/xtypes/TCollectionTypes.hpp
    include/dds/core/xtypes/DynamicData.hpp
    include/dds/core/xtypes/MemberType.hpp
    include/dds/core/xtypes/TTypeProvider.hpp
    include/dds/core/xtypes/TypeProvider.hpp
    include/dds/core/xtypes/TMemberType.hpp
    include/dds/core/xtypes/PrimitiveTypes.hpp
    include/dds/core/xtypes/TStructType.hpp
    include/dds/core/xtypes/TAnnotation.hpp
    include/dds/core/ddscore.hpp
    include/dds/core/QosProvider.hpp
    include/dds/core/LengthUnlimited.hpp
    include/dds/core/types.hpp
    include/dds/core/Duration.hpp
    include/dds/core/BuiltinTopicTypes.hpp
    include/dds/core/policy/PolicyKind.hpp
    include/dds/core/policy/detail/TQosPolicyCountImpl.hpp
    include/dds/core/policy/detail/CorePolicy.hpp
    include/dds/core/policy/detail/TCorePolicyImpl.hpp
    include/dds/core/policy/detail/QosPolicyCount.hpp
    include/dds/core/policy/CorePolicy.hpp
    include/dds/core/policy/TQosPolicyCount.hpp
    include/dds/core/policy/TCorePolicy.hpp
    include/dds/core/policy/QosPolicyCount.hpp
    include/dds/core/Exception.hpp
    include/dds/core/Entity.hpp
    include/dds/topic/AnyTopic.hpp
    include/dds/topic/TAnyTopic.hpp
    include/dds/topic/TMultiTopic.hpp
    include/dds/topic/BuiltinTopic.hpp
    include/dds/topic/ContentFilteredTopic.hpp
    include/dds/topic/TBuiltinTopic.hpp
    include/dds/topic/TFilter.hpp
    include/dds/topic/MultiTopic.hpp
    include/dds/topic/qos/TopicQos.hpp
    include/dds/topic/qos/detail/TopicQos.hpp
    include/dds/topic/TBuiltinTopicKey.hpp
    include/dds/topic/ddstopic.hpp
    include/dds/topic/TContentFilteredTopic.hpp
    include/dds/topic/TTopicDescription.hpp
    include/dds/topic/TTopic.hpp
    include/dds/topic/discovery.hpp
    include/dds/topic/detail/AnyTopic.hpp
    include/dds/topic/detail/BuiltinTopic.hpp
    include/dds/topic/detail/ContentFilteredTopic.hpp
    include/dds/topic/detail/MultiTopic.hpp
    include/dds/topic/detail/TFilterImpl.hpp
    include/dds/topic/detail/ddstopic.hpp
    include/dds/topic/detail/TTopicImpl.hpp
    include/dds/topic/detail/TContentFilteredTopicImpl.hpp
    include/dds/topic/detail/TAnyTopicImpl.hpp
    include/dds/topic/detail/discovery.hpp
    include/dds/topic/detail/find.hpp
    include/dds/topic/detail/TopicDescription.hpp
    include/dds/topic/detail/Filter.hpp
    include/dds/topic/detail/TBuiltinTopicImpl.hpp
    include/dds/topic/detail/TopicInstanceImpl.hpp
    include/dds/topic/detail/TBuiltinTopicKeyImpl.hpp
    include/dds/topic/detail/Topic.hpp
    include/dds/topic/detail/BuiltinTopicKey.hpp
    include/dds/topic/detail/TTopicDescriptionImpl.hpp
    include/dds/topic/find.hpp
    include/dds/topic/TopicDescription.hpp
    include/dds/topic/TopicListener.hpp
    include/dds/topic/Filter.hpp
    include/dds/topic/TopicInstance.hpp
    include/dds/topic/Topic.hpp
    include/dds/topic/BuiltinTopicKey.hpp
    include/dds/topic/AnyTopicListener.hpp
    include/dds/topic/TopicTraits.hpp
    include/dds/dds.hpp
    include/dds/sub/SampleRef.hpp
    include/dds/sub/AnyDataReaderListener.hpp
    include/dds/sub/SubscriberListener.hpp
    include/dds/sub/TDataReader.hpp
    include/dds/sub/AnyDataReader.hpp
    include/dds/sub/qos/SubscriberQos.hpp
    include/dds/sub/qos/detail/SubscriberQos.hpp
    include/dds/sub/qos/detail/DataReaderQos.hpp
    include/dds/sub/qos/DataReaderQos.hpp
    include/dds/sub/TRank.hpp
    include/dds/sub/TSample.hpp
    include/dds/sub/DataReader.hpp
    include/dds/sub/TQuery.hpp
    include/dds/sub/status/detail/DataStateImpl.hpp
    include/dds/sub/status/DataState.hpp
    include/dds/sub/TGenerationCount.hpp
    include/dds/sub/cond/TQueryCondition.hpp
    include/dds/sub/cond/TReadCondition.hpp
    include/dds/sub/cond/QueryCondition.hpp
    include/dds/sub/cond/detail/TQueryConditionImpl.hpp
    include/dds/sub/cond/detail/QueryCondition.hpp
    include/dds/sub/cond/detail/ReadCondition.hpp
    include/dds/sub/cond/detail/TReadConditionImpl.hpp
    include/dds/sub/cond/ReadCondition.hpp
    include/dds/sub/SharedSamples.hpp
    include/dds/sub/TCoherentAccess.hpp
    include/dds/sub/TSampleRef.hpp
    include/dds/sub/discovery.hpp
    include/dds/sub/DataReaderListener.hpp
    include/dds/sub/SampleInfo.hpp
    include/dds/sub/detail/SampleRef.hpp
    include/dds/sub/detail/Manipulators.hpp
    include/dds/sub/detail/TAnyDataReaderImpl.hpp
    include/dds/sub/detail/SamplesHolder.hpp
    include/dds/sub/detail/AnyDataReader.hpp
    include/dds/sub/detail/TSampleRefImpl.hpp
    include/dds/sub/detail/TSampleImpl.hpp
    include/dds/sub/detail/TSampleInfoImpl.hpp
    include/dds/sub/detail/TCoherentAccessImpl.hpp
    include/dds/sub/detail/DataReader.hpp
    include/dds/sub/detail/SharedSamplesImpl.hpp
    include/dds/sub/detail/SharedSamples.hpp
    include/dds/sub/detail/TGenerationCountImpl.hpp
    include/dds/sub/detail/discovery.hpp
    include/dds/sub/detail/TQueryImpl.hpp
    include/dds/sub/detail/SampleInfo.hpp
    include/dds/sub/detail/find.hpp
    include/dds/sub/detail/LoanedSamples.hpp
    include/dds/sub/detail/Subscriber.hpp
    include/dds/sub/detail/Sample.hpp
    include/dds/sub/detail/Rank.hpp
    include/dds/sub/detail/LoanedSamplesImpl.hpp
    include/dds/sub/detail/GenerationCount.hpp
    include/dds/sub/detail/Query.hpp
    include/dds/sub/detail/CoherentAccess.hpp
    include/dds/sub/detail/ddssub.hpp
    include/dds/sub/detail/TDataReaderImpl.hpp
    include/dds/sub/detail/TSubscriberImpl.hpp
    include/dds/sub/detail/TRankImpl.hpp
    include/dds/sub/find.hpp
    include/dds/sub/LoanedSamples.hpp
    include/dds/sub/Subscriber.hpp
    include/dds/sub/Sample.hpp
    include/dds/sub/Rank.hpp
    include/dds/sub/TAnyDataReader.hpp
    include/dds/sub/GenerationCount.hpp
    include/dds/sub/Query.hpp
    include/dds/sub/TSubscriber.hpp
    include/dds/sub/CoherentAccess.hpp
    include/dds/sub/ddssub.hpp
    include/dds/sub/TSampleInfo.hpp
    include/dds/pub/TPublisher.hpp
    include/dds/pub/DataWriter.hpp
    include/dds/pub/CoherentSet.hpp
    include/dds/pub/AnyDataWriterListener.hpp
    include/dds/pub/qos/DataWriterQos.hpp
    include/dds/pub/qos/detail/DataWriterQos.hpp
    include/dds/pub/qos/detail/PublisherQos.hpp
    include/dds/pub/qos/PublisherQos.hpp
    include/dds/pub/AnyDataWriter.hpp
    include/dds/pub/Publisher.hpp
    include/dds/pub/discovery.hpp
    include/dds/pub/TAnyDataWriter.hpp
    include/dds/pub/detail/TCoherentSetImpl.hpp
    include/dds/pub/detail/DataWriter.hpp
    include/dds/pub/detail/DataWriterImpl.hpp
    include/dds/pub/detail/CoherentSet.hpp
    include/dds/pub/detail/AnyDataWriter.hpp
    include/dds/pub/detail/Publisher.hpp
    include/dds/pub/detail/discovery.hpp
    include/dds/pub/detail/find.hpp
    include/dds/pub/detail/TAnyDataWriterImpl.hpp
    include/dds/pub/detail/ddspub.hpp
    include/dds/pub/detail/SuspendedPublication.hpp
    include/dds/pub/detail/TPublisherImpl.hpp
    include/dds/pub/detail/TSuspendedPublicationImpl.hpp
    include/dds/pub/find.hpp
    include/dds/pub/ddspub.hpp
    include/dds/pub/SuspendedPublication.hpp
    include/dds/pub/PublisherListener.hpp
    include/dds/pub/DataWriterListener.hpp
    include/dds/pub/TSuspendedPublication.hpp
    include/dds/pub/TCoherentSet.hpp
    include/dds/domain/DomainParticipantListener.hpp
    include/dds/domain/qos/detail/DomainParticipantQos.hpp
    include/dds/domain/qos/DomainParticipantQos.hpp
    include/dds/domain/DomainParticipant.hpp
    include/dds/domain/discovery.hpp
    include/dds/domain/detail/DomainParticipant.hpp
    include/dds/domain/detail/TDomainParticipantImpl.hpp
    include/dds/domain/detail/ddsdomain.hpp
    include/dds/domain/find.hpp
    include/dds/domain/ddsdomain.hpp
    include/dds/domain/TDomainParticipant.hpp
  )

if (ENABLE_QOS_PROVIDER)
  list(APPEND sources
    src/org/eclipse/cyclonedds/core/QosProviderDelegate.cpp)
endif()

if(BUILD_SHARED_LIBS OR NOT DEFINED BUILD_SHARED_LIBS)
  add_library(ddscxx SHARED ${sources})
else()
  add_library(ddscxx ${sources})
endif()

# SOVERSION should increase on incompatible ABI change
set_target_properties(ddscxx PROPERTIES VERSION ${PROJECT_VERSION} SOVERSION ${PROJECT_VERSION_MAJOR})

if(ENABLE_LEGACY)
  target_compile_definitions(ddscxx PUBLIC "DDSCXX_USE_BOOST")
endif()

# Create a pseudo-target that other targets (i.e. examples, tests) can depend
# on and can also be provided as import-target by a package-file when building
# those targets outside the regular Cyclone build-tree (i.e. the installed tree)
add_library(${PROJECT_NAME}::ddscxx ALIAS ddscxx)

add_coverage(ddscxx)

set_property(TARGET ddscxx PROPERTY CXX_STANDARD ${cyclonedds_cpp_std_to_use})

target_link_libraries(ddscxx PUBLIC CycloneDDS::ddsc)
target_include_directories(
  ddscxx
  PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/ddscxx>)

generate_export_header(
  ddscxx
  BASE_NAME OMG_DDS_API_DETAIL
  EXPORT_MACRO_NAME OMG_DDS_API_DETAIL
  EXPORT_FILE_NAME "include/dds/core/detail/export.hpp")

install(
  TARGETS ddscxx
  EXPORT "${PROJECT_NAME}"
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT lib
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT lib
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT lib)

install(
  DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/dds"
            "${CMAKE_CURRENT_BINARY_DIR}/include/dds"
            "${CMAKE_CURRENT_SOURCE_DIR}/include/org"
  DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/ddscxx"
  COMPONENT dev)

if(BUILD_TESTING)
  add_subdirectory(tests)
endif()
